### ISSUE TITLE
Google Play Publishing Warnings

### ISSUE THREAD

**Issue by stickboyc** [torch2424/picoDeploy#35]
Received the following warning when uploading a build to Google Play today.

```
Warning
This release is not compliant with the Google Play 64-bit requirement

The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code: 200002.

From August 1, 2019 all releases must be compliant with the Google Play 64-bit requirement.

Include 64-bit and 32-bit native code in your app. Use the Android App Bundle publishing format to automatically ensure that each device architecture receives only the native code it needs. This avoids increasing the overall size of your app. Learn More
```

Didn't halt submission, but will starting in August.

The build I uploaded was the `armv7` version.

Is this user error or do we need to update the code to "proof" it for this upcoming update?

**Comment by torch2424** [comment]
@stickboyc 

Hello, so yeah, you also need to upload the 64 bit version 😄 From #34 , I saw that it generated the 64 bit file for you. So you just need to sign and upload that as well 👍

**Comment by stickboyc** [comment]
So user error, my apologies for blowing up your notifications :P

**Comment by torch2424** [comment]
@stickboyc No worries! :smile:
