### ISSUE TITLE
Unable to run / install 

### ISSUE THREAD

**Issue by novusabeo** [torch2424/picoDeploy#36]
npm run ionic:serve

> picoDeploy@0.0.1 ionic:serve /home/johnny/Projects/PICO/picoDeploy-master
> npm run config && npm run cart && ionic-app-scripts serve

> picoDeploy@0.0.1 config /home/johnny/Projects/PICO/picoDeploy-master
> node config/copyConfig.js

Using the following config: picoDeployConfig.json

> picoDeploy@0.0.1 cart /home/johnny/Projects/PICO/picoDeploy-master
> rm -rf www/cart && mkdir www/cart && cp -r cart/* www/cart

mkdir: cannot create directory ‘www/cart’: No such file or directory

npm ERR! Linux 4.15.0-64-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "cart"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! picoDeploy@0.0.1 cart: `rm -rf www/cart && mkdir www/cart && cp -r cart/* www/cart`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the picoDeploy@0.0.1 cart script 'rm -rf www/cart && mkdir www/cart && cp -r cart/* www/cart'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the picoDeploy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf www/cart && mkdir www/cart && cp -r cart/* www/cart
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs picoDeploy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls picoDeploy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/johnny/Projects/PICO/picoDeploy-master/npm-debug.log

npm ERR! Linux 4.15.0-64-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "ionic:serve"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! picoDeploy@0.0.1 ionic:serve: `npm run config && npm run cart && ionic-app-scripts serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the picoDeploy@0.0.1 ionic:serve script 'npm run config && npm run cart && ionic-app-scripts serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the picoDeploy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run config && npm run cart && ionic-app-scripts serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs picoDeploy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls picoDeploy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/johnny/Projects/PICO/picoDeploy-master/npm-debug.log

**Comment by novusabeo** [comment]
Running Elementary OS (ubuntu 18)

**Comment by torch2424** [comment]
Ah! I've been super busy lately, but once I'm done moving I'll check this out 😄 @novusabeo

**Comment by Chovin** [comment]
does this issue cover `npm install` failing?

**Comment by torch2424** [comment]
@novusabeo Sorry I haven't taken a look at this yet 😢 After moving (which I'm still slowly unpacking), I had a huge debacle with Spotify outside of my music stuff, and been catching up with a lot of friends. I also switched jobs recently and stuff, so it's just been a lot going on 😢 

@Chovin It seems like this does.

I'll try and take a look as soon as I can. Currently flying to give a talk at a conference!

**Comment by torch2424** [comment]
@novusabeo WAYYYY overdue, but I finally did a fix for this. Just had to updated the dependencies, and use [mkdirp](https://www.npmjs.com/package/mkdirp) to fix the script 😄
